altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  7a8c37b3-0707-4702-9588-0097d44e643d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-09T23:45:16+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4c98db25-6292-44cd-9122-6da04f7b508f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 900213ad-8bc0-4402-ac06-360592570b37
        userCondition: null
fs: system
handle: system
name: System
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: dist
transformSubpath: ''
